# Generated by Django 2.1 on 2020-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISE2_INFRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISE2_INFRA_id', models.IntegerField(default=0)),
                ('infrasonido_1', models.FloatField(default=0)),
                ('infrasonido_2', models.FloatField(default=0)),
                ('infrasonido_3', models.FloatField(default=0)),
                ('infrasonido_4', models.FloatField(default=0)),
                ('infrasonido_5', models.FloatField(default=0)),
                ('posicion', models.CharField(max_length=200)),
                ('fecha_recepcion', models.DateTimeField(verbose_name='fecha_captura')),
            ],
        ),
    ]
