# Generated by Django 2.1 on 2020-03-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ise2_infra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ise2_infra',
            name='ISE2_INFRA_id',
        ),
        migrations.RemoveField(
            model_name='ise2_infra',
            name='posicion',
        ),
    ]
